# Central Volumes Image
volumes:
  image: tianon/true
  volumes:
    # YouTransfer
    - "./node-red/:/root/.node-red"



# Node-Red
nodered:
  image: beevelop/node-red
  expose:
    - "1880"
  volumes_from:
    - "volumes"
  restart: always
