# Central Volumes Image
volumes:
  image: tianon/true
  volumes:
    # YouTransfer
    - "./node-red/:/root/.node-red"

# Central NGINX-Proxy
proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
  restart: always

# Node-Red
nodered:
  image: beevelop/node-red
  environment:
    - VIRTUAL_HOST=35.233.128.209
    - VIRTUAL_PORT=1880
  expose:
    - "1880"
  volumes_from:
    - "volumes"
  restart: always
